project_id = "wlbdscnfizpqsfcezrnn"

[auth.password_protection]
enabled = true

[functions.admin-users]
verify_jwt = true

[functions.create-checkout-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.update-password]
verify_jwt = true